### ISSUE TITLE
Can the renderers property under licenseReport extension accept keyword instead of new object

### ISSUE THREAD

**Issue by amimas** [jk1/Gradle-License-Report#86] opened 2018-07-06 16:28 UTC
Hello,

I'm just getting started with this plugin and it's looking very interesting. One problem I ran into is that I cannot use my modularized approach for managing gradle scripts.

Currently, if we want an HTML report, after applying the plugin, this is how we should be doing configuring it.

```gradle
import com.github.jk1.license.render.*

licenseReport {
    renderers = [new InventoryHtmlReportRenderer()]
}
```
I have my build organized in multiple gradle files. For example, I have a `build.gradle` under the root project. Inside this `build.gradle`, I have very generic configurations, such as `buildScript`, `plugins`, some variables, group name, project version, etc. After that I use `apply from` to include different build configurations like this:

```gradle
apply from: 'gradle/coverage.gradle'
apply from: 'gradle/publishing.gradle'
apply from: 'gradle/code-quality.gradle'
apply from: 'gradle/dependency-report.gradle'
``` 

The problem with this approach comes up when I need to **import** any classes. For example, this plugin requires importing the render package if I want to generate different types of report as per my example above. Gradle doesn't seem to like it. I get error like this:

```
* What went wrong:
Could not compile script '/Users/amimas/myproject/master/gradle/dependency-license.gradle'.
> startup failed:
  script '/Users/amimas/myproject/master/gradle/dependency-license.gradle': 12: unable to resolve class InventoryHtmlReportRenderer 
   @ line 12, column 15.
        renderers = [new InventoryHtmlReportRenderer()]
                   ^
  
  1 error
```

The only way I can use a different renderer to generate an HTML report is if I put the configurations in the main `build.gradle` file where the plugin is being applied from. I haven't found any fix or workaround for this.

That's why I was thinking if it is possible for the `render` property to accept keywords. For example:

```gradle
licenseReport {
    renderers = [inventoryHtml, xml, csv]
}
```
this will generate 3 reports that corresponds to those keywords. Problem with this approach is when you need to pass additional parameters/options for each of those reports.

Not sure if there are any other options.

**Comment by jk1** [comment] 2018-07-06 16:50
How about FQCN?

```groovy
licenseReport {
    renderers = [new com.github.jk1.license.render.InventoryHtmlReportRenderer()]
}
```

It may look a bit awkward but requires no imports.

**Comment by amimas** [comment] 2018-07-06 17:33
Nope. That didn't seem to help either. Still getting same error:

```
* What went wrong:
Could not compile script '/Users/amimas/myproject/master/gradle/dependency-license.gradle'.
> startup failed:
  script '/Users/amimas/myproject//master/gradle/dependency-license.gradle': 12: unable to resolve class com.github.jk1.license.render.InventoryHtmlReportRenderer 
   @ line 12, column 15.
        renderers = [new com.github.jk1.license.render.InventoryHtmlReportRenderer()]
 ```

**Comment by jk1** [comment] 2018-07-06 19:53
That means this is not the import problem, but rather a class missing from the classpath.
Could you please provide me with a minimal build file example, that reproduces the problem?

**Comment by amimas** [comment] 2018-07-06 20:08
Sure, here's what I have.

`build.gradle`:
```gradle
plugins {
	id 'com.github.jk1.dependency-license-report' version '1.0'
}

ext.javaVersion = 1.8
ext.product = 'My Project'
group = 'com.amimas.project1'
version = '1.0-SNAPSHOT'

apply from: 'gradle/base.gradle'
apply from: 'gradle/dependency-license.gradle'
```

`gradle/dependency-license.gradle`:
```gradle
// import com.github.jk1.license.render.*
licenseReport {
	excludeGroups = ['com.amimas.project1'] //exclude project's own group
	renderers = [new com.github.jk1.license.render.InventoryHtmlReportRenderer()]
}
```

**Comment by guenhter** [comment] 2018-07-11 06:15
I guess this is no issue of plugin. When you want to use classes of a plugin in a externalized script (`dependency-license.gradle`), then you must tell gradle which classpath to use like it is possible with:

```
--> `gradle/dependency-license.gradle`
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.github.jk1:gradle-license-report:1.1"
  }
}
...
```

Does this help?

**Comment by amimas** [comment] 2018-07-11 18:08
I haven't tried it that way. Let me try it. I'll get back to you. Thanks for the suggestion.

**Comment by amimas** [comment] 2018-07-11 20:34
Unfortunately that doesn't seem to help either. I get this error:

```
➜  master git:(license-report) ✗ sh gradlew generateLicenseReport

FAILURE: Build failed with an exception.

* Where:
Script '/Users/amimas/myproject/master/gradle/dependency-license.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Could not find method licenseReport() for arguments [dependency_license_7x5aw4mzlpfxaqvj1q6a3sc26$_run_closure1@656adc72] on root project 'master' of type org.gradle.api.Project.
```
I agree that this is not particularly plugin issue. I ran into same issue with other plugins too when I need to import classes from the applied plugin in a separate Gradle script being imported. I think this is a Gradle specific issue and I don't know enough internal details to comment on it. Haven't seen any workaround for this either.

**Comment by guenhter** [comment] 2018-10-17 05:57
Sorry for the late response. Just tried this out: It works the following way:

`build.gradle`:
```
apply from: 'report.gradle'
```

`report.gradle`
```
import com.github.jk1.license.LicenseReportPlugin
import com.github.jk1.license.render.InventoryHtmlReportRenderer

buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.github.jk1:gradle-license-report:1.3"
  }
}

apply plugin: LicenseReportPlugin

licenseReport {
    renderers = [new InventoryHtmlReportRenderer()]
}
```

Important is

**Comment by guenhter** [comment] 2019-01-22 14:57
@amimas Can you confirm that this works?

**Comment by amimas** [comment] 2019-01-25 23:21
@guenhter I recently changed job and don't have projects where I can easily test this out.

**Comment by guenhter** [comment] 2019-01-28 06:42
@amimas How should we proceed? Should we close this?

**Comment by amimas** [comment] 2019-01-28 15:20
I'm okay with it being closed for now.

**Closed** 2019-01-28 15:22 UTC

**Comment by flitzie** [comment] 2020-01-10 10:42
Hello,

I can confirm the following solution (for Gradle 5.2.1 and GLR 0.12):

```gradle
buildscript {
   repositories {
      // ...
   }
   dependencies {
      classpath "com.github.jk1:gradle-license-report:${licenseReportVersion}"
   }
}

apply plugin: com.github.jk1.license.LicenseReportPlugin

import com.github.jk1.license.render.*
import com.github.jk1.license.filter.*

licenseReport {
   // ...
}
```
Instead of using `apply plugin: com.github.jk1.license.LicenseReportPlugin` this works too:
```gradle
apply plugin: LicenseReportPlugin
import com.github.jk1.license.LicenseReportPlugin
```
But for me preferring Gradles plugin Id block the combination of externalized gradle files seems not to work properly with this plugin and using import statements.
Normally I just do this in a rootProject / subProject build.gradle file with other Gradle plugins:
```gradle
// in rootProject
plugins {
   id 'com.github.jk1.dependency-license-report' version '1.12' apply false
}
// in subProject
apply plugin: 'com.github.jk1.dependency-license-report'
```
But as soon as I do `apply plugin: 'com.github.jk1.dependency-license-report'` in an **externalized** build file it says "unknow plugin id". This is very strange because the jar file
`C:\Users\xyz\.gradle\caches\modules-2\files-2.1\com.github.jk1\gradle-license-report\1.12\5bf6b18b5c43032b5c3327138d5a3b7cf647220b\gradle-license-report-1.12.jar\META-INF\gradle-plugins\com.github.jk1.dependency-license-report.properties`
points to `implementation-class=com.github.jk1.license.LicenseReportPlugin`. Which is correct.
For my understanding of Gradle this seems a bit odd.

But maybe you have an idea why this does not work with plugin-ids?

Thanks for your reply in advance.
